"""Object storage for uploaded documents.

Anchor does not keep production documents on a container filesystem: that is
wiped on every deploy. The storage key is stored in Postgres and the bytes live
in S3 (or its compatible equivalents), so a re-index can re-read the original
years later.

Two drivers implement the same four operations. ``local`` is the development
default and writes under ``STORAGE_LOCAL_DIR``; ``s3`` is what production must
use. Both refuse a key that escapes its root, because the key is built from a
user-supplied document name.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from agent.config import get_settings
from agent.observability.logger import get_logger

log = get_logger(__name__)

#: Characters allowed in a storage key segment. Document names are user input
#: and end up in a path (local) and in an S3 key, so they are reduced to a
#: conservative alphabet rather than escaped.
_SAFE_SEGMENT = re.compile(r"[^A-Za-z0-9._-]+")


class StorageError(RuntimeError):
    """The object store could not satisfy the request."""


@dataclass(frozen=True, slots=True)
class StoredObject:
    key: str
    size_bytes: int
    content_type: str


def build_key(workspace_id: str, document_id: str, filename: str) -> str:
    """Compose a storage key that cannot escape its prefix.

    The workspace and document ids are UUIDs generated by Anchor, so they need
    no escaping; only the filename does. Two documents with the same name in
    different workspaces therefore get different keys, which is what makes
    per-workspace deletion safe.
    """
    cleaned = _SAFE_SEGMENT.sub("-", filename).strip("-._") or "document.pdf"
    return f"{workspace_id}/{document_id}/{cleaned[:120]}"


class Storage(Protocol):
    def put(self, key: str, data: bytes, content_type: str) -> StoredObject: ...
    def get(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...


class LocalStorage:
    """Filesystem driver for development and tests."""

    def __init__(self, root: str | None = None) -> None:
        self.root = Path(root or get_settings().STORAGE_LOCAL_DIR).resolve()

    def _resolve(self, key: str) -> Path:
        candidate = (self.root / key).resolve()
        # Belt and braces: `key` is already sanitised by build_key, but this is
        # the last place a traversal could take effect, so it is checked here.
        if not candidate.is_relative_to(self.root):
            raise StorageError("Refused a storage key outside the storage root.")
        return candidate

    def put(self, key: str, data: bytes, content_type: str = "application/pdf") -> StoredObject:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return StoredObject(key=key, size_bytes=len(data), content_type=content_type)

    def get(self, key: str) -> bytes:
        path = self._resolve(key)
        try:
            return path.read_bytes()
        except OSError as exc:
            raise StorageError("The document could not be read from storage.") from exc

    def delete(self, key: str) -> None:
        path = self._resolve(key)
        try:
            path.unlink(missing_ok=True)
        except OSError as exc:
            raise StorageError("The document could not be removed from storage.") from exc

    def exists(self, key: str) -> bool:
        return self._resolve(key).is_file()


class S3Storage:
    """Amazon S3 (or any S3-compatible endpoint).

    The client is built lazily so importing this module does not require
    credentials, and so a misconfigured bucket surfaces at upload time with a
    clear message rather than at import.
    """

    def __init__(self) -> None:
        settings = get_settings()
        if not settings.S3_BUCKET:
            raise StorageError(
                "STORAGE_BACKEND is 's3' but S3_BUCKET is not set. See .env.example."
            )
        self.bucket = settings.S3_BUCKET
        self.prefix = settings.S3_KEY_PREFIX.strip("/")
        self._client = None
        self._settings = settings

    @property
    def client(self):
        if self._client is None:
            try:
                import boto3
            except ImportError as exc:  # pragma: no cover - packaging guard
                raise StorageError("STORAGE_BACKEND is 's3' but boto3 is not installed.") from exc
            self._client = boto3.client(
                "s3",
                region_name=self._settings.S3_REGION or None,
                endpoint_url=self._settings.S3_ENDPOINT_URL or None,
                aws_access_key_id=self._settings.S3_ACCESS_KEY_ID or None,
                aws_secret_access_key=self._settings.S3_SECRET_ACCESS_KEY or None,
            )
        return self._client

    def _full_key(self, key: str) -> str:
        return f"{self.prefix}/{key}" if self.prefix else key

    def put(self, key: str, data: bytes, content_type: str = "application/pdf") -> StoredObject:
        try:
            self.client.put_object(
                Bucket=self.bucket,
                Key=self._full_key(key),
                Body=data,
                ContentType=content_type,
            )
        except Exception as exc:
            # The vendor's message can contain the bucket name and a request
            # id; neither belongs in a response body.
            log.error("storage.put_failed", context={"key": key}, exc_info=True)
            raise StorageError("The document could not be stored.") from exc
        return StoredObject(key=key, size_bytes=len(data), content_type=content_type)

    def get(self, key: str) -> bytes:
        try:
            response = self.client.get_object(Bucket=self.bucket, Key=self._full_key(key))
            return bytes(response["Body"].read())
        except Exception as exc:
            log.error("storage.get_failed", context={"key": key}, exc_info=True)
            raise StorageError("The document could not be read from storage.") from exc

    def delete(self, key: str) -> None:
        try:
            self.client.delete_object(Bucket=self.bucket, Key=self._full_key(key))
        except Exception as exc:
            log.error("storage.delete_failed", context={"key": key}, exc_info=True)
            raise StorageError("The document could not be removed from storage.") from exc

    def exists(self, key: str) -> bool:
        try:
            self.client.head_object(Bucket=self.bucket, Key=self._full_key(key))
            return True
        except Exception:
            return False


_storage: Storage | None = None


def get_storage() -> Storage:
    """The configured storage driver."""
    global _storage
    if _storage is None:
        backend = get_settings().STORAGE_BACKEND
        _storage = S3Storage() if backend == "s3" else LocalStorage()
        log.info("storage.ready", context={"backend": backend})
    return _storage


def reset_storage() -> None:
    global _storage
    _storage = None


def copy_local_into(source: Path, key: str) -> StoredObject:
    """Convenience for the local batch-ingestion worker."""
    return get_storage().put(key, source.read_bytes(), "application/pdf")


def purge_workspace_directory(workspace_id: str) -> None:
    """Remove every local object for a workspace. Used when a workspace is deleted."""
    if get_settings().STORAGE_BACKEND != "local":
        return
    root = Path(get_settings().STORAGE_LOCAL_DIR).resolve() / workspace_id
    if root.is_dir():
        shutil.rmtree(root, ignore_errors=True)
